apiVersion: apps/v1
kind: Deployment
metadata:
 name: bulletin-board
spec:
 replicas: 2
 selector:
    matchLabels:
      app: bulletin-board
 template:
   metadata: 
     labels:
       app: bulletin-board
   spec:
     containers:
     - name: bulletin-board
       image: demonccc/bulletin-board-app:latest
       ports:
       - containerPort: 8080
