apiVersion: v1
kind: Service
metadata:
 name: bulletin-board
spec:
 type: NodePort
 selector:
   app: bulletin-board 
 ports:
   - protocol: TCP
     port: 80
     targetPort: 8080
     nodePort: 30001
